insert into public.hotels (name, description, price_per_night, location, amenities, photos, status) values
('Hotel Turístico D''Conchis', 'Hospedaje acogedor a minutos del centro de Tingo María, ideal para comenzar la aventura.', 60, 'Tingo María, Huánuco', array['Wi‑Fi','Desayuno','Estacionamiento'], array['https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=85'], 'active'),
('Caruzo Hotel', 'Comodidad, atención local y una ubicación práctica para descubrir la Bella Durmiente.', 100, 'Tingo María, Huánuco', array['Wi‑Fi','Piscina','Aire acondicionado','Desayuno'], array['https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=85'], 'active'),
('Hotel Madera Verde', 'Un refugio cálido rodeado de verde, pensado para descansar después de cada tour.', 150, 'Tingo María, Huánuco', array['Wi‑Fi','Piscina','Restaurante','Estacionamiento'], array['https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=85'], 'active');
insert into public.experiences (name, description, price, duration, meeting_point, category, photos, status, is_featured) values
('Río y Catarata Derrepente', 'Caminata entre selva y baño refrescante en Cayumba. Traslado desde hotel o Plaza de Armas incluido.', 80, 'Día completo', 'Plaza de Armas de Tingo María', 'Naturaleza', array['https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=85'], 'active', true),
('Catarata Honolulu', 'Una ruta vibrante hacia una de las caídas de agua más queridas de la zona. Traslado desde hotel o Plaza de Armas incluido.', 60, '5 horas', 'Plaza de Armas de Tingo María', 'Cataratas', '{}', 'active', false),
('Cueva Hayna Cápac', 'Explora formaciones naturales y las historias escondidas de la selva. Traslado desde hotel o Plaza de Armas incluido.', 50, '4 horas', 'Plaza de Armas de Tingo María', 'Aventura', '{}', 'active', false),
('Cueva de las Lechuzas', 'Recorre el Parque Nacional Tingo María y observa su fauna emblemática. Traslado con punto de encuentro acordado.', 45, '4 horas', 'Entrada del Parque Nacional', 'Naturaleza', '{}', 'active', false),
('Bosque de Piedras', 'Paisajes rocosos extraordinarios para caminar y fotografiar. Traslado desde hotel o Plaza de Armas incluido.', 90, 'Día completo', 'Plaza de Armas de Tingo María', 'Aventura', '{}', 'active', false),
('La Bella Durmiente', 'Mirador y relato local frente a la silueta más famosa de Tingo María. Traslado desde hotel o Plaza de Armas incluido.', 30, '2 horas', 'Plaza de Armas de Tingo María', 'Cultura', '{}', 'active', false),
('City tour Tingo María', 'Sabores, historia y rincones locales de la ciudad. Traslado desde hotel o Plaza de Armas incluido.', 40, '3 horas', 'Plaza de Armas de Tingo María', 'Cultura', '{}', 'active', false);
