'use client';
import { useMemo, useState } from 'react';
import { ExperienceCard, HotelCard } from './catalog';
import type { Experience, Hotel } from '@/lib/types';

export function ExperienceCatalog({experiences}:{experiences:Experience[]}){const [search,setSearch]=useState('');const [category,setCategory]=useState('Todas');const [maxPrice,setMaxPrice]=useState(150);const categories=['Todas',...Array.from(new Set(experiences.map(x=>x.category)))];const filtered=useMemo(()=>experiences.filter(x=>(category==='Todas'||x.category===category)&&Number(x.price)<=maxPrice&&`${x.name} ${x.description} ${x.category}`.toLowerCase().includes(search.toLowerCase())),[experiences,search,category,maxPrice]);return <><div className="filter-panel mb-7"><div className="grid gap-5 lg:grid-cols-[1fr_auto]"><label className="block text-sm font-semibold text-forest">Busca una aventura<input className="input mt-2" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Catarata, cueva, city tour..."/></label><label className="block text-sm text-forest lg:w-52">Presupuesto: <b>S/{maxPrice}</b><input className="mt-3 block w-full accent-amber" type="range" min="30" max="150" step="10" value={maxPrice} onChange={e=>setMaxPrice(Number(e.target.value))}/></label></div><div className="mt-5 flex gap-2 overflow-x-auto pb-1">{categories.map(c=><button key={c} onClick={()=>setCategory(c)} className={`chip whitespace-nowrap ${category===c?'chip-active':''}`}>{c}</button>)}</div></div><p className="mb-5 text-sm text-forest/60">{filtered.length} experiencia{filtered.length!==1?'s':''} disponible{filtered.length!==1?'s':''}</p><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{filtered.map(e=><ExperienceCard key={e.id} experience={e}/>)}</div>{!filtered.length&&<Empty reset={()=>{setSearch('');setCategory('Todas');setMaxPrice(150)}}/>}</>}
type HotelTier='all'|'essential'|'balanced'|'premium';
export function HotelCatalog({hotels,initialTier='all'}:{hotels:Hotel[];initialTier?:string}){const validTier=['all','essential','balanced','premium'].includes(initialTier)?initialTier as HotelTier:'all';const [search,setSearch]=useState('');const [maxPrice,setMaxPrice]=useState(200);const [tier,setTier]=useState<HotelTier>(validTier);const sorted=[...hotels].sort((a,b)=>Number(a.price_per_night)-Number(b.price_per_night));const group=Math.max(1,Math.ceil(sorted.length/3));const lowLimit=Number(sorted[group-1]?.price_per_night||0);const highLimit=Number(sorted[sorted.length-group]?.price_per_night||Infinity);const filtered=useMemo(()=>hotels.filter(x=>{const price=Number(x.price_per_night);const inTier=tier==='all'||(tier==='essential'&&price<=lowLimit)||(tier==='balanced'&&price>lowLimit&&price<highLimit)||(tier==='premium'&&price>=highLimit);return inTier&&price<=maxPrice&&`${x.name} ${x.location} ${x.amenities.join(' ')}`.toLowerCase().includes(search.toLowerCase())}),[hotels,search,maxPrice,tier,lowLimit,highLimit]);return <><div className="filter-panel mb-7"><div className="grid gap-5 sm:grid-cols-[1fr_220px]"><label className="block text-sm font-semibold text-forest">Busca hospedaje<input className="input mt-2" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Nombre, zona o servicio..."/></label><label className="block text-sm text-forest">Presupuesto: <b>S/{maxPrice}</b><input className="mt-3 block w-full accent-amber" type="range" min="50" max="200" step="10" value={maxPrice} onChange={e=>setMaxPrice(Number(e.target.value))}/></label></div><div className="mt-5 flex gap-2 overflow-x-auto pb-1">{([['all','Todos'],['essential','Esencial'],['balanced','Equilibrado'],['premium','Superior']] as const).map(([value,label])=><button key={value} className={`chip whitespace-nowrap ${tier===value?'chip-active':''}`} onClick={()=>setTier(value)}>{label}</button>)}</div></div><p className="mb-5 text-sm text-forest/60">{filtered.length} hospedaje{filtered.length!==1?'s':''} disponible{filtered.length!==1?'s':''}</p><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{filtered.map(h=><HotelCard key={h.id} hotel={h}/>)}</div>{!filtered.length&&<Empty reset={()=>{setSearch('');setMaxPrice(200);setTier('all')}}/>}</>}
function Empty({reset}:{reset:()=>void}){return <div className="rounded-2xl bg-white p-8 text-center"><p className="font-display text-2xl text-forest">No encontramos resultados</p><button className="mt-3 text-sm font-semibold underline" onClick={reset}>Limpiar filtros</button></div>}
